// GlobalComponents for Volar
declare module 'vue' {
  export interface GlobalComponents {
    TwAffix: typeof import('../packages/tw-element')['TwAffix']
    TwAlert: typeof import('../packages/tw-element')['TwAlert']
    TwAside: typeof import('../packages/tw-element')['TwAside']
    TwAutocomplete: typeof import('../packages/tw-element')['TwAutocomplete']
    TwAvatar: typeof import('../packages/tw-element')['TwAvatar']
    TwBacktop: typeof import('../packages/tw-element')['TwBacktop']
    TwBadge: typeof import('../packages/tw-element')['TwBadge']
    TwBreadcrumb: typeof import('../packages/tw-element')['TwBreadcrumb']
    TwBreadcrumbItem: typeof import('../packages/tw-element')['TwBreadcrumbItem']
    TwButton: typeof import('../packages/tw-element')['TwButton']
    TwButtonGroup: typeof import('../packages/tw-element')['TwButtonGroup']
    TwCalendar: typeof import('../packages/tw-element')['TwCalendar']
    TwCard: typeof import('../packages/tw-element')['TwCard']
    TwCarousel: typeof import('../packages/tw-element')['TwCarousel']
    TwCarouselItem: typeof import('../packages/tw-element')['TwCarouselItem']
    TwCascader: typeof import('../packages/tw-element')['TwCascader']
    TwCascaderPanel: typeof import('../packages/tw-element')['TwCascaderPanel']
    TwCheckbox: typeof import('../packages/tw-element')['TwCheckbox']
    TwCheckboxButton: typeof import('../packages/tw-element')['TwCheckboxButton']
    TwCheckboxGroup: typeof import('../packages/tw-element')['TwCheckboxGroup']
    TwCol: typeof import('../packages/tw-element')['TwCol']
    TwCollapse: typeof import('../packages/tw-element')['TwCollapse']
    TwCollapseItem: typeof import('../packages/tw-element')['TwCollapseItem']
    TwCollapseTransition: typeof import('../packages/tw-element')['TwCollapseTransition']
    TwColorPicker: typeof import('../packages/tw-element')['TwColorPicker']
    TwContainer: typeof import('../packages/tw-element')['TwContainer']
    TwConfigProvider: typeof import('../packages/tw-element')['TwConfigProvider']
    TwDatePicker: typeof import('../packages/tw-element')['TwDatePicker']
    TwDialog: typeof import('../packages/tw-element')['TwDialog']
    TwDivider: typeof import('../packages/tw-element')['TwDivider']
    TwDrawer: typeof import('../packages/tw-element')['TwDrawer']
    TwDropdown: typeof import('../packages/tw-element')['TwDropdown']
    TwDropdownItem: typeof import('../packages/tw-element')['TwDropdownItem']
    TwDropdownMenu: typeof import('../packages/tw-element')['TwDropdownMenu']
    TwEmpty: typeof import('../packages/tw-element')['TwEmpty']
    TwFooter: typeof import('../packages/tw-element')['TwFooter']
    TwForm: typeof import('../packages/tw-element')['TwForm']
    TwFormItem: typeof import('../packages/tw-element')['TwFormItem']
    TwHeader: typeof import('../packages/tw-element')['TwHeader']
    TwIcon: typeof import('../packages/tw-element')['TwIcon']
    TwImage: typeof import('../packages/tw-element')['TwImage']
    TwImageViewer: typeof import('../packages/tw-element')['TwImageViewer']
    TwInput: typeof import('../packages/tw-element')['TwInput']
    TwInputNumber: typeof import('../packages/tw-element')['TwInputNumber']
    TwLink: typeof import('../packages/tw-element')['TwLink']
    TwMain: typeof import('../packages/tw-element')['TwMain']
    TwMenu: typeof import('../packages/tw-element')['TwMenu']
    TwMenuItem: typeof import('../packages/tw-element')['TwMenuItem']
    TwMenuItemGroup: typeof import('../packages/tw-element')['TwMenuItemGroup']
    TwOption: typeof import('../packages/tw-element')['TwOption']
    TwOptionGroup: typeof import('../packages/tw-element')['TwOptionGroup']
    TwPageHeader: typeof import('../packages/tw-element')['TwPageHeader']
    TwPagination: typeof import('../packages/tw-element')['TwPagination']
    TwPopconfirm: typeof import('../packages/tw-element')['TwPopconfirm']
    TwPopper: typeof import('../packages/tw-element')['TwPopper']
    TwProgress: typeof import('../packages/tw-element')['TwProgress']
    TwRadio: typeof import('../packages/tw-element')['TwRadio']
    TwRadioButton: typeof import('../packages/tw-element')['TwRadioButton']
    TwRadioGroup: typeof import('../packages/tw-element')['TwRadioGroup']
    TwRate: typeof import('../packages/tw-element')['TwRate']
    TwRow: typeof import('../packages/tw-element')['TwRow']
    TwScrollbar: typeof import('../packages/tw-element')['TwScrollbar']
    TwSelect: typeof import('../packages/tw-element')['TwSelect']
    TwSlider: typeof import('../packages/tw-element')['TwSlider']
    TwStep: typeof import('../packages/tw-element')['TwStep']
    TwSteps: typeof import('../packages/tw-element')['TwSteps']
    TwSubMenu: typeof import('../packages/tw-element')['TwSubMenu']
    TwSwitch: typeof import('../packages/tw-element')['TwSwitch']
    TwTabPane: typeof import('../packages/tw-element')['TwTabPane']
    TwTable: typeof import('../packages/tw-element')['TwTable']
    TwTableColumn: typeof import('../packages/tw-element')['TwTableColumn']
    TwTabs: typeof import('../packages/tw-element')['TwTabs']
    TwTag: typeof import('../packages/tw-element')['TwTag']
    TwTimePicker: typeof import('../packages/tw-element')['TwTimePicker']
    TwTimeSelect: typeof import('../packages/tw-element')['TwTimeSelect']
    TwTimeline: typeof import('../packages/tw-element')['TwTimeline']
    TwTimelineItem: typeof import('../packages/tw-element')['TwTimelineItem']
    TwTooltip: typeof import('../packages/tw-element')['TwTooltip']
    TwTransfer: typeof import('../packages/tw-element')['TwTransfer']
    TwTree: typeof import('../packages/tw-element')['TwTree']
    TwTreeV2: typeof import('../packages/tw-element')['TwTreeV2']
    TwUpload: typeof import('../packages/tw-element')['TwUpload']
    TwSpace: typeof import('../packages/tw-element')['TwSpace']
    TwSkeleton: typeof import('../packages/tw-element')['TwSkeleton']
    TwSkeletonItem: typeof import('../packages/tw-element')['TwSkeletonItem']
    TwCheckTag: typeof import('../packages/tw-element')['TwCheckTag']
    TwDescriptions: typeof import('../packages/tw-element')['TwDescriptions']
    TwDescriptionsItem: typeof import('../packages/tw-element')['TwDescriptionsItem']
    TwResult: typeof import('../packages/tw-element')['TwResult']
    TwSelectV2: typeof import('../packages/tw-element')['TwSelectV2']
  }
}

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $message: typeof import('../packages/tw-element')['TwMessage']
    $notify: typeof import('../packages/tw-element')['TwNotification']
    $msgbox: typeof import('../packages/tw-element')['TwMessageBox']
    $messageBox: typeof import('../packages/tw-element')['TwMessageBox']
    $alert: typeof import('../packages/tw-element')['TwMessageBox']['alert']
    $confirm: typeof import('../packages/tw-element')['TwMessageBox']['confirm']
    $prompt: typeof import('../packages/tw-element')['TwMessageBox']['prompt']
    $loading: typeof import('../packages/tw-element')['TwLoadingService']
  }
}

export {}
